---
- name: copy harbor CA cert to nodes
  hosts: k3s_cluster
  become: true
  gather_facts: true
  tasks:
    - name: Copy harbor CA cert to nodes
      ansible.builtin.copy:
        src: ../files/harbor-ca.crt
        dest: /etc/rancher/k3s/harbor-ca.crt
        owner: root
        group: root
        mode: "0644"
    
    - name: Copy harbor TLS cert to nodes
      ansible.builtin.copy:
        src: ../files/harbor-tls.crt
        dest: /etc/rancher/k3s/harbor-tls.crt
        owner: root
        group: root
        mode: "0644"

    - name: Copy harbor TLS key to nodes
      ansible.builtin.copy:
        src: ../files/harbor-tls.key
        dest: /etc/rancher/k3s/harbor-tls.key
        owner: root
        group: root
        mode: "0644"

    - name: Restart k3s to apply harbor CA cert
      ansible.builtin.systemd:
        name: k3s
        state: restarted
      when: "'server' in group_names"
    
    - name: Restart k3s-agent to apply harbor CA cert
      ansible.builtin.systemd:
        name: k3s-agent
        state: restarted
      when: "'agent' in group_names"